COFFEE/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='Home'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path, re_path
from. import views

app_name="Home"
urlpatterns = [
    path(r'index/', views.index, name='index'),
    path(r'HotGoods/', views.HotGoods,name="HotGoods"),
    path(r'notice/', views.notice,name="notice"),
    path(r'comment/', views.comment,name="comment"),
    path(r'register/',views.register,name='register'),
    re_path(r'^goods/(?P<goodsID>[0-9]+)$',views.goods,name='goods'),
    path(r'cart/',views.cart,name='cart'),
    path(r'logOut/',views.logOut,name='logOut'),
    path(r'buy/',views.buy,name='buy'),
    path(r'search/',views.search,name='search')
]

Home/models.py
from django.db import models

# Create your models here.


class GoodsInfo(models.Model):
    goodsID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    photo = models.ImageField(upload_to="Home/GoodsP")
    price = models.IntegerField()
    introduce = models.TextField(null=True)
    sale = models.IntegerField(null=True)
    stroe = models.IntegerField(null=True)
    brand = models.ForeignKey(
        "brand", to_field='brandID', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class brand(models.Model):
    brandID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name


class user(models.Model):
    userID = models.AutoField(primary_key=True)
    userName = models.CharField(max_length=32)
    avatar = models.ImageField(upload_to='Home/avatar')
    sex = models.CharField(max_length=32)
    password = models.TextField()
    name = models.CharField(max_length=32)
    phone = models.IntegerField()
    email = models.EmailField()
    address = models.TextField()

    def __str__(self):
        return self.name


class message(models.Model):
    messageID = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    content = models.TextField()
    time = models.DateTimeField(auto_now=True)
    userID = models.ForeignKey(
        'user', to_field="userID", on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class notice(models.Model):
    noticeID = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    content = models.TextField()
    time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class order(models.Model):
    orderID = models.AutoField(primary_key=True)
    userID = models.ForeignKey('user',to_field='userID',on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)
    price = models.IntegerField()

class orderList(models.Model):
    ID = models.AutoField(primary_key=True)
    orderID = models.ForeignKey('order',to_field='orderID',on_delete=models.CASCADE)

Home/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from. import models


def index(req):
    Goods = models.GoodsInfo.objects.all()
    if req.session.get('is_login', False):
        user = models.user.objects.get(userName=req.session['user_name'])
        return render(req, 'Home/index.html', {"goods": Goods, 'user': user})

    if req.method == "POST":
        username = req.POST.get('username', None)
        password = req.POST.get('password', None)
        message = '用户名和密码不能为空'
        if username and password:
            try:
                user = models.user.objects.get(userName=username)
                if user.password == password:
                    req.session['is_login'] = True
                    req.session['user_id'] = user.userID
                    req.session['user_name'] = user.userName
                    return render(req, 'Home/index.html', {'goods': Goods, 'user': user})
                else:
                    message = '密码错误！'
            except:
                message = '此用户不存在！'
            return render(req, 'Home/index.html', {'goods': Goods, 'message': message})
        return render(req, 'Home/index.html', {'Goods': Goods, 'message': message})
    else:
        return render(req, 'Home/index.html', {"goods": Goods})


def HotGoods(req):
    Goods=models.GoodsInfo.objects.all()
    goods=[]
    length=len(Goods)-1
    for i in range(0,12):
        goods.append(Goods[length])
        length=length-1
    return render(req, 'Home/HotGoods.html',{'goods':goods})


def notice(req):
    notices = models.notice.objects.all()
    return render(req, 'Home/notice.html',{'notices': notices})


def comment(req):
    if req.method =='POST':
        content=req.POST.get('text')
        title='用户评论'
        id=req.session['user_id']
        userID=models.user.objects.get(pk=id)
        models.message.objects.create(title=title,content=content,userID=userID)
    messages = models.message.objects.all()
    return render(req, 'Home/comment.html', {'messages':messages})


def register(req):
    userName = req.POST.get('username')
    name = req.POST.get('name')
    password = req.POST.get('password')
    avatar = req.POST.get('avatar')
    sex = req.POST.get('gender')
    phone = req.POST.get('phone')
    email = req.POST.get('email')
    address = req.POST.get('address')
    models.user.objects.create(userName=userName, avatar=avatar, name=name,
                               sex=sex, password=password, phone=phone, email=email, address=address)
    return render(req, 'Home/register.html')


def goods(req, goodsID):
    goods = models.GoodsInfo.objects.get(pk=goodsID)
    return render(req, 'Home/goods.html', {'goods': goods})


def cart(req):
    if req.method == "POST":
        goodsID = req.POST.get('goodsID')
        goods = models.GoodsInfo.objects.get(pk=goodsID)
        req.session['goodspage'] = req.META.get('HTTP_REFERER', '/')
        count = int(req.POST.get('count'))
        totlePrice = req.session.get('totlePrice', None)
        if not totlePrice:
            req.session['totlePrice'] = count*goods.price
        else:
            totlePrice += count*goods.price
            req.session['totlePrice'] = totlePrice
        item = {'goodsID': goodsID, 'name': goods.name,
                'photo': goods.photo, 'price': goods.price, 'quantity': count}
        cart = req.session.get("cart", None)
        if not cart:
            cart = []
            cart.append(item)
            req.session['cart'] = cart
        else:
            for i in cart:
                if i['goodsID'] == goodsID:
                    i['quantity'] += count
                    return redirect(req.session['goodspage'])
            cart.append(item)
        return redirect(req.session['goodspage'])
    else:
        cart = req.session.get("cart", None)
        totlePrice = req.session.get('totlePrice', None)
        if not cart:
            return render(req, 'Home/cart.html')
        return render(req, 'Home/cart.html', {'cart': cart, 'totlePrice': totlePrice})


def logOut(req):
    req.session['is_login'] = False
    req.session['index'] = req.META.get('HTTP_REFERER', '/')
    return redirect(req.session['index'])

def buy(req):
    cart=req.session.get('cart',None)
    userID=req.session.get('user_id',None)
    totlePrice=req.session.get('totlePrice',None)
    is_login=req.session.get('is_login',False)
    if is_login:
        user=models.user.objects.get(pk=userID)
        return render(req,"Home/buy.html",{'cart':cart,'user':user,'totlePrice':totlePrice})
    else:
        message='请先返回首页登录'
        return render(req,'Home/buy.html',{'message':message})

def search(req):
    bra = req.POST.get('Search')
    brand=models.brand.objects.get(name=bra)
    goods = models.GoodsInfo.objects.filter(brand=brand.brandID)
    return render(req,'Home/search.html',{'goods':goods,'bra':bra})
        

Home/templates/Home/HotGoods.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'Home/css/index.css' %}">
</head>

<body>
    <div class="mid" style="background-image:url({% static 'Home/images/body.jpeg' %}); background-size:100% 100%">
        <nav>
            <ul class="nav nav-tabs nav-justified">
                <li role="presentation"><a href="{% url 'Home:index' %}">首页</a></li>
                <li role="presentation" class="active"><a href="{% url 'Home:HotGoods' %}">最新上架</a></li>
                <li role="presentation"><a href="{% url 'Home:notice' %}">公告</a></li>
                <li role="presentation"><a href="{% url 'Home:comment' %}">留言板</a></li>
            </ul>
        </nav>
        <div class="slider">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="{% static 'Home/images/3.jpeg' %}" alt="First slide">
                        <div class="carousel-caption">
                            <h3>咖啡予讲台 </h3>
                            <p>一杯咖啡让讲台上劳累的你身心舒畅</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5501.jpeg' %}" alt="Second slide">
                        <div class="carousel-caption">
                            <h3>咖啡予工作</h3>
                            <p>一杯咖啡让电脑前焦虑的你沉着自信</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5504.jpeg' %}" alt="Third slide">
                        <div class="carousel-caption">
                            <h3>咖啡予休闲 </h3>
                            <p>一杯咖啡陪伴让你和时光更加静谧</p>
                        </div>
                    </div>
                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="con">
            <div class="row">
                {% for good in goods %}
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <a href="{% url 'Home:goods' good.goodsID %}">
                            <img src="{{MEDIA_URL}}{{good.photo}}" alt="...">
                            <div class="caption">
                                <h3>{{good.Name}}</h3>
                                <p>{{good.introduce}}</p>
                                <p class="extra"><span class="glyphicon glyphicon-thumbs-up"></span>
                                    {{good.sale}}人说好</p>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot-up">
            <span>专属你的COFFF驿站</span>
        </div>
        <div class="foot-down">
            <span>网站导航</span>
            <a href="http://127.0.0.1:8000/index/"><span>首页</span></a>
            <a href="http://www.shufe.edu.cn/structure/index.psp" target="_blank"><span>上海财经大学</span></a>
            <a href="https://www.taobao.com/" target="_blank"><span>淘宝网</span></a>
            <a href="https://www.jd.com/" target="_blank"><span>京东</span></a>
        </div>
    </div>

    <script>
        $(".avatar").mouseover(function () {
            $(".panel").css("display", "block")
        })
        $(".panel").mouseover(function () {
            $(".panel").css("display", "block")
        }).mouseout(function () {
            $(".panel").css("display", "none")
        })

        $("#btn").click(function () {
            if ($('#btn').text() == "注册") {
                $(this).text('登录')
                $('.form1').css('display', 'none');
                $('.form2').css('display', 'block');
            } else {
                $(this).text('注册')
                $('.form1').css('display', 'block');
                $('.form2').css('display', 'none');
            }
        })
    </script>
</body>

</html>

Home/templates/Home/comment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'Home/css/comment.css' %}">
</head>

<body>
    <div class="mid" style="background-image:url({% static 'Home/images/body.jpeg' %}); background-size:100% 100%">
        <nav>
            <ul class="nav nav-tabs nav-justified">
                <li role="presentation"><a href="{% url 'Home:index' %}">首页</a></li>
                <li role="presentation"><a href="{% url 'Home:HotGoods' %}">最新上架</a></li>
                <li role="presentation"><a href="{% url 'Home:notice' %}">公告</a></li>
                <li role="presentation" class="active"><a href="{% url 'Home:comment' %}">留言板</a></li>
            </ul>
        </nav>
        <div class="slider">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="{% static 'Home/images/3.jpeg' %}" alt="First slide">
                        <div class="carousel-caption">
                            <h3>咖啡予讲台 </h3>
                            <p>一杯咖啡让讲台上劳累的你身心舒畅</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5501.jpeg' %}" alt="Second slide">
                        <div class="carousel-caption">
                            <h3>咖啡予工作</h3>
                            <p>一杯咖啡让电脑前焦虑的你沉着自信</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5504.jpeg' %}" alt="Third slide">
                        <div class="carousel-caption">
                            <h3>咖啡予休闲 </h3>
                            <p>一杯咖啡陪伴让你和时光更加静谧</p>
                        </div>
                    </div>
                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="con">
            {% for message in messages %}
            <div class="comment">
                <div class='left'><img class='avatar' src="{{MEDIA_URL}}{{message.userID.avatar}}"></div>
                <div class='right'>
                    <div class='rig-name'>{{message.userID.userName}}</div>
                    <div class='rig-con'>{{message.content}}</div>
                    <div class='rig-tim'>{{message.time}}</div>
                </div>
            </div>
            {% endfor %}
            <div class='bot'>
                我要留言
            </div>
            <div class='liuyan' >
                <form action="{% url 'Home:comment' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name='text'>
                    <button type='submit'>提交</button>
                </form>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot-up">
            <span>专属你的COFFF驿站</span>
        </div>
        <div class="foot-down">
            <span>网站导航</span>
            <a href="http://127.0.0.1:8000/index/"><span>首页</span></a>
            <a href="http://www.shufe.edu.cn/structure/index.psp" target="_blank"><span>上海财经大学</span></a>
            <a href="https://www.taobao.com/" target="_blank"><span>淘宝网</span></a>
            <a href="https://www.jd.com/" target="_blank"><span>京东</span></a>
        </div>
    </div>

    <script>
        $(".avatar").mouseover(function () {
            $(".panel").css("display", "block")
        })
        $(".panel").mouseover(function () {
            $(".panel").css("display", "block")
        }).mouseout(function () {
            $(".panel").css("display", "none")
        })

        $("#btn").click(function () {
            if ($('#btn').text() == "注册") {
                $(this).text('登录')
                $('.form1').css('display', 'none');
                $('.form2').css('display', 'block');
            } else {
                $(this).text('注册')
                $('.form1').css('display', 'block');
                $('.form2').css('display', 'none');
            }
        })

        $('.bot').click(function(){
            $(this).css('display','None')
            $('.liuyan').css('display','block')
        })
    </script>
</body>

</html>

Home/templates/Home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'Home/css/index.css' %}">
</head>

<body>
    <div class='header' style="background-image:url({% static 'Home/images/head2.jpeg' %}); background-size:100% 100%">
        <div class="container">
            {% if request.session.is_login %}
            <div class='log-reg'>
                <img class='avatar' src="{{MEDIA_URL}}{{user.avatar}}">
                <span class="nickName">{{user.userName}}</span>
                <a href="{% url 'Home:cart' %}"><span class='glyphicon glyphicon-shopping-cart'></span></a>
                <a class='log-out' href="{% url 'Home:logOut' %}">注销</a>
            </div>
            {% else %}
            <div class="log-reg">
                <img class="avatar" src="///img.alicdn.com/tfs/TB1.0VvChjaK1RjSZFAXXbdLFXa-80-80.png">
                <div class="panel">
                    <i class="arrow"></i>
                    <div class="content">
                        <span>登录可购买商品哦</span>
                    </div>
                    <div class="bottom-sign">
                        <a href="javascript:void(0)" class="sign" data-toggle="modal" data-target="#myModal">登录/注册</a>
                    </div>
                </div>
            </div>
            {% endif %}
            <div id="search">
                <form id="search-box" action="/search/" method="POST" >
                    {% csrf_token %}
                    <input id="h-inp" type="text" name="Search" placeholder="品牌直通车">
                    <button type="submit">GO</button>
                </form>
            </div>
        </div>
    </div>
    <div id="myModal" class="modal video-modal fade" tabindex="-1" role="dialog" aria-labelledby="myModal"
        style="display:none" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    账号登录和注册
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <section>
                    <div class="modal-body">
                        <div class="form1" style="display:block">
                            <form class="bs-example bs-example-form" action="{% url 'Home:index' %}" method="POST">
                                {% csrf_token %}
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </span>
                                    <input type="text" class="form-control" name="username" placeholder="用户名">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-lock"></span>
                                    </span>
                                    <input type="password" class="form-control" name='password' placeholder="请输入密码">
                                </div>
                                <input type="submit" class='btn1' value="登录">
                            </form>
                        </div>
                        <div class="form2" style="display: none">
                            <form class="bs-example bs-example-form" action="/register/" method="post">
                                {% csrf_token %}
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </span>
                                    <input type="text" class="form-control" name="username" placeholder="用户名">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </span>
                                    <input type="text" class="form-control" name="name" placeholder="真实姓名">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-lock"></span>
                                    </span>
                                    <input type="password" class="form-control" name='password' placeholder="密码">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-lock"></span>
                                    </span>
                                    <input type="password" class="form-control" name='password' placeholder="再此输入密码">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-phone"></span>
                                    </span>
                                    <input type="text" class="form-control" name='phone' placeholder="手机号码">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-envelope"></span>
                                    </span>
                                    <input type="email" class="form-control" name='email' placeholder="邮箱">
                                </div>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-home"></span>
                                    </span>
                                    <input type="text" class="form-control" name='address' placeholder="地址（2宿420)">
                                </div>
                                <div class="gender">
                                    <span>性别:</span>
                                    <div><input type="radio" name='gender' value='男' checked="checked">男</div>
                                    <div><input type="radio" name='gender' value='女'>女</div>
                                </div>
                                <div class='upload-avatar'>
                                    <span>上传头像:</span>
                                    <input type="file" name="avatar">
                                </div>
                                <input type="submit" class='btn1' value="注册">
                            </form>
                        </div>
                        <div class='btn-log'><button id="btn" type="button" class='btn btn-default'
                                value="注册">注册</button></div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="mid" style="background-image:url({% static 'Home/images/body.jpeg' %}); background-size:100% 100%">
        <nav>
            <ul class="nav nav-tabs nav-justified">
                <li role="presentation" class="active"><a href="{% url 'Home:index' %}">首页</a></li>
                <li role="presentation"><a href="{% url 'Home:HotGoods' %}">最新上架</a></li>
                <li role="presentation"><a href="{% url 'Home:notice' %}">公告</a></li>
                <li role="presentation"><a href="{% url 'Home:comment' %}">留言板</a></li>
            </ul>
        </nav>
        <div class="slider">
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
                <!-- 轮播（Carousel）指标 -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- 轮播（Carousel）项目 -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="{% static 'Home/images/3.jpeg' %}" alt="First slide">
                        <div class="carousel-caption">
                            <h3>咖啡予讲台 </h3>
                            <p>一杯咖啡让讲台上劳累的你身心舒畅</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5501.jpeg' %}" alt="Second slide">
                        <div class="carousel-caption">
                            <h3>咖啡予工作</h3>
                            <p>一杯咖啡让电脑前焦虑的你沉着自信</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="{% static 'Home/images/5504.jpeg' %}" alt="Third slide">
                        <div class="carousel-caption">
                            <h3>咖啡予休闲 </h3>
                            <p>一杯咖啡陪伴让你和时光更加静谧</p>
                        </div>
                    </div>
                </div>
                <!-- 轮播（Carousel）导航 -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="con">
            <div class="row">
                {% for good in goods %}
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <a href="{% url 'Home:goods' good.goodsID %}">
                            <img src="{{MEDIA_URL}}{{good.photo}}" alt="...">
                            <div class="caption">
                                <h3>{{good.Name}}</h3>
                                <p>{{good.introduce}}</p>
                                <p class="extra"><span class="glyphicon glyphicon-thumbs-up"></span>
                                    {{good.sale}}人说好</p>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot-up">
            <span>专属你的COFFF驿站</span>
        </div>
        <div class="foot-down">
            <span>网站导航</span>
            <a href="http://127.0.0.1:8000/index/"><span>首页</span></a>
            <a href="http://www.shufe.edu.cn/structure/index.psp" target="_blank"><span>上海财经大学</span></a>
            <a href="https://www.taobao.com/" target="_blank"><span>淘宝网</span></a>
            <a href="https://www.jd.com/" target="_blank"><span>京东</span></a>
        </div>
    </div>
    {% if message %}
    <script>
        alert('{{message}}')
    </script>
    {% endif %}

    <script>
        $(".avatar").mouseover(function () {
            $(".panel").css("display", "block")
        })
        $(".panel").mouseover(function () {
            $(".panel").css("display", "block")
        }).mouseout(function () {
            $(".panel").css("display", "none")
        })

        $("#btn").click(function () {
            if ($('#btn').text() == "注册") {
                $(this).text('登录')
                $('.form1').css('display', 'none');
                $('.form2').css('display', 'block');
            } else {
                $(this).text('注册')
                $('.form1').css('display', 'block');
                $('.form2').css('display', 'none');
            }
        })
        function logOut() {
            request.session.is_login = false;
            window.location.reload();
        }
    </script>
</body>

</html>